### ISSUE TITLE
关于实现的细节还有几点疑问

### ISSUE THREAD

**Issue by LiaoChenyi** [sses7757/CS307_2022Fall_Project2_QA#1]
一、希望能够把Export Checking之前的状态变化也详细说明一下，解释一下"A retrieval courier can only set an item of his/her correspondence to state as far as “Export Checking” while a delivery courier can only set an item of his/her correspondence to state as far as “Finish""的具体含义。
二、在newItem()方法中有关数据合法性的问题。
①能不能输入之前没有的class?
②输入的ItemState能为null吗？
③Retrieval city 和 Delivery city 能不能相同？ Export city 和 Import city 能不能相同？ 它们中能不能有null？
④Retrieval city 和 Delivery city 对应的staff的类别一定是Courier吗？ Export city 和 Import city对应的staff的类别一定是Seaport Officer吗?这些staff都能为null吗？
希望能够尽快解答这些疑问，十分感谢各位助教对此的付出。

**Comment by LogicDX342** [comment]
Local Judge的数据貌似和`A retrieval courier can only set an item of his/her correspondence`这一描述有出入，answer里不同的Retrieval Courier可以对同一Item进行操作

**Comment by sses7757** [comment]
> 一、希望能够把Export Checking之前的状态变化也详细说明一下，解释一下"A retrieval courier can only set an item of his/her correspondence to state as far as “Export Checking” while a delivery courier can only set an item of his/her correspondence to state as far as “Finish""的具体含义。 二、在newItem()方法中有关数据合法性的问题。 ①能不能输入之前没有的class? ②输入的ItemState能为null吗？ ③Retrieval city 和 Delivery city 能不能相同？ Export city 和 Import city 能不能相同？ 它们中能不能有null？ ④Retrieval city 和 Delivery city 对应的staff的类别一定是Courier吗？ Export city 和 Import city对应的staff的类别一定是Seaport Officer吗?这些staff都能为null吗？ 希望能够尽快解答这些疑问，十分感谢各位助教对此的付出。

已经更新
其他问题：
①应该不会给没有的class
③三个问题应该都是不能的，具体`newItem`什么可以为null，麻烦看一下更新的说明或者文档。
④两个问题都是的，你可以看一下sakai上最新版的data.zip，local judge中的data会在更新完local judge之后一起上传；第三个问题同上。

**Comment by sses7757** [comment]
> Local Judge的数据貌似和`A retrieval courier can only set an item of his/her correspondence`这一描述有出入，answer里不同的Retrieval Courier可以对同一Item进行操作

麻烦再看一下这个Q&A库的说明：
> If the current local judge returns otherwise, please refer to this Q&A supplement since it will be updated more often.
