### ISSUE TITLE
一些困惑

### ISSUE THREAD

**Issue by creegon** [sses7757/CS307_2022Fall_Project2_QA#2]
一：集装箱里面如果没有物品，也可以被装到船上么（或者说会进行这样的操作么）？
二：getAllItemsAtPort的，是要返回在这个（出口/进口）城市的所有处于进口检查/出口检查的物品么？（就它可能既是出口又是进口城市？）（另外打印出来的顺序没有影响吧？）
三：角色检查时，是直接在API里面if判断一下就行了把？
四：在卸载货物时，是不是会把这个货物的船上的所有货物一起卸载下来？

**Comment by sses7757** [comment]
> 一：集装箱里面如果没有物品，也可以被装到船上么（或者说会进行这样的操作么）？ 二：getAllItemsAtPort的，是要返回在这个（出口/进口）城市的所有处于进口检查/出口检查的物品么？（就它可能既是出口又是进口城市？）（另外打印出来的顺序没有影响吧？） 三：角色检查时，是直接在API里面if判断一下就行了把？ 四：在卸载货物时，是不是会把这个货物的船上的所有货物一起卸载下来？

1. 我记得是不会进行这样的操作，否则你的数据库就需要维护container本身的状态了
2. 是的，顺序没有影响
3. 理论上judge不会检查每一个用户的角色和权限，但是会有一点检查，你可以看具体local judge文件
4. 不会，所有对item的操作都是以item为单位的，你再看一下`unloadItem`说明。你想一下，如果所有货物一起卸下的话，装船的货物就必须进口城市一样了，这现实起来更复杂了

**Comment by creegon** [comment]
蟹蟹解答！还有一小点，关于loadContainerToShip的，我理解的是要满足以下几点：
1.container里面的物品的状态只能是PackingToContainer
2.ship对应的item中，没有状态为Shipping的
3.权限只能为CompanyManager。
不知道我理解的是否有偏差？谢谢老师了

**Comment by sses7757** [comment]
> 蟹蟹解答！还有一小点，关于loadContainerToShip的，我理解的是要满足以下几点： 1.container里面的物品的状态只能是PackingToContainer 2.ship对应的item中，没有状态为Shipping的 3.权限只能为CompanyManager。 不知道我理解的是否有偏差？谢谢老师了

应该是对的
