### ISSUE TITLE
关于localjudge中newItem方法测试数据的一个问题

### ISSUE THREAD

**Issue by QY02** [sses7757/CS307_2022Fall_Project2_QA#4]
助教好！在之前关于newItem的问题中，回答是export city和import city不能相同，但在localjudge中有一个例子这两个城市相同但返回值是true，请问这种情况是应该返回true还是false呢，谢谢！
![屏幕截图 2022-12-18 162411](https://user-images.githubusercontent.com/63695294/208288614-d867dd91-9480-4a6f-9fb4-cee92373bcf0.png)

**Comment by HaoyuWang2001** [comment]
而且该例子中，item price=999，tax rate for (Shanghai, apple, export) is 0.68, 因此，出口关税(export tax)应为999*0.68=679.32，而itemInfo中给的export tax为132.0 。请问是我什么地方考虑的不对吗？
![image](https://user-images.githubusercontent.com/108910511/208304352-c32791a8-132b-4582-a1d9-868bc959fe52.png)

**Comment by WLS2002** [comment]
确实是一个bug，我们会尽快解决。

**Comment by QY02** [comment]
好的，非常感谢！
