### ISSUE TITLE
非root用户的API发生异常时是否需要删除也如题中所说删除所有的表？

### ISSUE THREAD

**Issue by Estraie** [sses7757/CS307_2022Fall_Project2_QA#5]
如题。

**Comment by sses7757** [comment]
理论上来讲，异常处理是实现内部的事情，judge不会管理这个。如果实现把异常抛到外面，jUnit会标记这个测试为不通过。至于之后的API通不通过，是实现的事情。
删除表的操作事实上是judge下次启动后自动运行的，理论上不需要实现来操作，你可以看一下local judge代码。

**Comment by WLS2002** [comment]
不需要
